name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Modules
        run: yarn

      - name: Run ESLint
        run: yarn lint

      - name: Heroku Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'recipe-finder-challenge' #Must be unique in Heroku
          heroku_email: 'santamaria.migue@gmail.com'
